name: app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- FRESHIO ML & CAMERA DEPENDENCIES ---
  # To run the AI Model
  tflite_flutter: ^0.12.1

  # To pick existing photos from the Gallery
  image_picker: ^1.0.7

  # Image manipulation library
  image: ^4.7.2
  
  # To use the device camera for real-time inspection
  camera: ^0.10.5+9 

  # For requesting camera permissions from the user
  permission_handler: ^11.3.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # --- ASSETS CONFIGURATION ---
  assets:
    - assets/model/Freshio_model_v02.tflite
    - assets/model/labels.txt

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/freshio_icon.png"
  min_sdk_android: 21