name: app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- FRESHIO ML & CAMERA DEPENDENCIES ---
  # Library to run the AI Model
  tflite_flutter: ^0.10.4

  # Library to pick existing photos from the Gallery
  image_picker: ^1.0.7
  # Image manipulation library
  image: ^4.7.2
  
  # To use the device camera for real-time inspection
  camera: ^0.10.5+9 
  # For requesting camera permissions from the user
  permission_handler: ^11.3.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # --- ASSETS CONFIGURATION ---
  # This tells the app to bundle your model files
  assets:
    - assets/model/Freshio_model_v01.tflite
    - assets/model/labels.txt