name: app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- ADDED FOR FRESHIO ---
  # Library to run the AI Model
  tflite_flutter: ^0.10.4
  # Library to open the Camera/Gallery
  image_picker: ^1.0.7
  image: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # --- ASSETS CONFIGURATION ---
  # This tells the app to bundle your model files
  assets:
    - assets/model/fruit_model.tflite
    - assets/model/labels.txt